version: "3"
services:
  node:
    build: ./api/
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    networks:
      - dockernet
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalog
    volumes: 
      - db:/var/lib/mysql
    networks:
      - dockernet
  php:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - dockernet
    depends_on:
      - node

volumes:
  db:

networks:
  dockernet:
    name: dockernet
    driver: bridge
