version: "3"
services:
  node:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"